config/routes.rb
Portfolio::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  scope "/admin" do
    resources :projects do
        get 'pictures'
    end
    resources :pictures, :only => [:index, :create, :edit, :update, :destroy]
  end

  match "home" => "home#index"
  match "home/show_project/:id" => "home#show_project", :as => :show_project

  root :to => 'home#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :caption, :file, :file_cache, :status, :subtype, :file_image, :feature_id, :feature_type, :remove_file
  belongs_to :feature, :polymorphic => true
  mount_uploader :file, FileUploader

  include Rails.application.routes.url_helpers

  def to_jq_upload
    {
      "name" => read_attribute(:file),
      "size" => file.size,
      "url" => file.url,
      "thumbnail_url" => file.thumb.url,
      "delete_url" => picture_path(:id => id),
      "delete_type" => "DELETE"
    }
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :customer_name, :description, :duration, :status, :tags, :title, :pictures_attributes
  has_many :pictures, :as => :feature
  accepts_nested_attributes_for :pictures, :reject_if => proc { |attributes| attributes['image'].blank? && attributes['image_cache'].blank? }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable
  #, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @projects = Project.all
  end

  def show_project
    @projects = Project.where(params[:id])
    @pictures = Project.find(params[:id]).pictures
    render 'project'
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  before_filter :authenticate_user!

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
  end

  def create
    @picture = Picture.new(params[:picture])
    if @picture.save
      respond_to do |format|
        format.html {
          render :json => [@picture.to_jq_upload].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json {
          render :json => [@picture.to_jq_upload].to_json
        }
      end
    else
      render :json => [{:error => "custom_failure"}], :status => 304
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to pictures_url, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json {     render :json => true }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @project.pictures.collect { |p| p.to_jq_upload }.to_json }
    end
  end

  def pictures
    @project = Project.find(params[:project_id])
    respond_to do |format|
      format.json { render :json => @project.pictures.collect { |p| p.to_jq_upload }.to_json }
      format.html
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save!
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message
    messages = ""
    [:notice, :info, :warning, :error].each {|type|
      if flash[type]
        messages += content_tag :div, flash.now[type], :class => "#{type}", :id => "alert"
      end
    }
    messages
  end
end

app/helpers/home_helper.rb
# -*- coding: utf-8 -*-
module HomeHelper

  def project_cover(project)
    cover = project.pictures.where(:subtype => 'cover' ).first
    link_to( image_tag(cover.file.url, class:"img-polaroid", "data-id" => project.id), show_project_url(project)) if cover
  end

  def project_customer_name(project)
    content_tag(:li, ("<strong>Cliente:</strong> " + project.customer_name).html_safe) unless project.customer_name.blank?
  end

  def project_duration(project)
    content_tag(:li, ("<strong>Duración:</strong> " + project.duration).html_safe) unless project.duration.blank?
  end

end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/_project_info.html.erb
<% content_for :sidebar do %>

  <% @projects.each do |project| %>
    <ul class="project_info" data-id="<%= project.id %>">

      <h1><%= project.title %></h1>
      <li><%= project.description %></li>
      <%= project_customer_name(project) %>
      <%= project_duration(project) %>
    </ul>

  <% end %>

<% end %>

app/views/home/index.html.erb
<% @projects.each do |project| %>
  <div class="cover">
    <h3><%= project.title %></h3>
    <%= project_cover(project) %>
    <i class="icon-tags"><%= project.tags %></i>
  </div>
<% end %>

<%= render "project_info" %>

app/views/home/project.html.erb
<%= render "project_info" %>

<div class="mygallery">
  <div class="tn3 album">
    <ol>
      <% @pictures.each do |picture| %>
        <li>
          <div class="tn3 description"> <%= picture.caption %> </div>
          <%= link_to(image_tag(picture.file.url), picture.file.url ) %>
        </li>
      <% end %>
    </ol>
  </div>
</div>

app/views/home/show.html.erb
<div class="mygallery">
  <div class="tn3 album">
    <ol>
      <% @pictures.each do |picture| %>
        <li>
          <h4>FOo</h4>
          <div class="tn3 description"> Bar </div>
          <%= link_to(image_tag(picture.file.url), picture.file.url ) %>
        </li>
      <% end %>
    </ol>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
 <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Yennifer Guisao Franco</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Portafolio", home_url %></li>
            <li><%= link_to "Sobre mí" %></li>
            <li><%= link_to "Contactame" %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'Projectos', projects_path %></li>
              <li><%= link_to 'Imagenes', pictures_path %></li>
              <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path,
              method: :delete %></li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <%= flash_message.html_safe %>
  <div class="container">
    <div class="row">
      <div class="span9">
        <%= yield %>
      </div>
      <div class="span3">
        <%= yield :sidebar %>
      </div>
    </div>
  </div>
  <div id="footer">
    <div class="container">
      <p class="muted credit">
        Diseño por Carlos Guisao Franco
      </p>
    </div>
  </div>
</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for @picture, :html => { :class => 'form-horizontal' } do |f| %>
<div class="control-group">
  <%= f.label :subtype, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :subtype, :class => 'text_field' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :caption, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :caption, :class => 'text_field' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :status, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :status, :class => 'text_field' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :file, :class => 'control-label' %>
  <div class="controls">
    <%= f.file_field :file %>
    <%= f.hidden_field :file_cache %>
    <label>
      <%= f.check_box :remove_file %>
      Remove File
    </label>
  </div>
</div>

<% content_for :sidebar do %>
      <%= image_tag(f.object.file_url,
                    :class => 'img-rounded') if f.object.file? %>
<% end %>

<div class="form-actions">
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      pictures_path, :class => 'btn' %>
</div>
<% end %>

app/views/pictures/_picture.html.erb
<%= image_tag(picture.file_url(:thumb), :class => 'img-rounded') if picture.file? %>

app/views/pictures/create.js.erb
<%# if this is the case then the validations have failed %>
<% if @picture.new_record? %>
  alert("Failed to upload painting: <%= j @picture.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#pictures").append("<%= j render(@picture) %>");
<% end %>

app/views/pictures/edit.html.erb
<%- model_class = Picture -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pictures/index.html.erb
<%- model_class = Picture -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:feature_type) %></th>
      <th><%= model_class.human_attribute_name(:subtype) %></th>
      <th><%= model_class.human_attribute_name(:caption) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:file) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.id %></td>
        <td><%= picture.feature_type %></td>
        <td><%= picture.subtype %></td>
        <td><%= picture.caption %></td>
        <td><%= picture.status %></td>
        <td><%= image_tag(picture.file_url(:thumb), :class =>
        'img-rounded') if picture.file? %></td>
        <td><%=l picture.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_picture_path(picture), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      picture_path(picture),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/_file_upload.html.erb
<h2>Upload Photos</h2>
<%= form_for Picture.new, :html => { :multipart => true,
    :id => "fileupload", "data-images" => project_pictures_url(@project) } do |f| %>

  <%# The fileupload-buttonbar contains buttons to add/delete - files
      and start/cancel the upload %>

  <%= f.hidden_field :feature_id, :value => @project.id %>
  <%= f.hidden_field :feature_type, :value =>  "Project" %>

<div class="row fileupload-buttonbar">
  <div class="span7">
    <%# The fileinput-button span is used to style the file input field as button %>

    <span class="btn btn-success fileinput-button">
      <i class="icon-plus icon-white"></i>
      <span>Add files...</span>
      <%= f.file_field :file, multiple: true, name: "picture[file]" %>
    </span>

    <button type="submit" class="btn btn-primary start">
      <i class="icon-upload icon-white"></i>
      <span>Start upload</span>
    </button>

    <button type="reset" class="btn btn-warning cancel">
      <i class="icon-ban-circle icon-white"></i>
      <span>Cancel upload</span>
    </button>

    <button type="button" class="btn btn-danger delete">
      <i class="icon-trash icon-white"></i>
      <span>Delete</span>
    </button>
    <input type="checkbox" class="toggle">
  </div>

  <div class="span5">
    <%# The global progress bar %>
    <div class="progress progress-success progress-striped active fade">
      <div class="bar" style="width:0%;"></div>
    </div>
  </div>
</div>

<%# The loading indicator is shown during image processing %>
<div class="fileupload-loading"></div>
<br>
<%# The table listing the files available for upload/download %>
<table class="table table-striped">
  <tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
</table>
<% end %>

<%# The template to display files available for upload %>
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td class="preview"><span class="fade"></span></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        {% if (file.error) { %}
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else if (o.files.valid && !i) { %}
            <td>
                <div class="progress progress-success progress-striped active">
                  <div class="bar" style="width:0%;"></div></div>
            </td>
            <td class="start">{% if (!o.options.autoUpload) { %}
                <button class="btn btn-primary">
                    <i class="icon-upload icon-white"></i>
                    <span>{%=locale.fileupload.start%}</span>
                </button>
            {% } %}</td>
        {% } else { %}
            <td colspan="2"></td>
        {% } %}
        <td class="cancel">{% if (!i) { %}
            <button class="btn btn-warning">
                <i class="icon-ban-circle icon-white"></i>
                <span>{%=locale.fileupload.cancel%}</span>
            </button>
        {% } %}</td>
    </tr>
{% } %}
</script>

<%# The template to display files available for download %>
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        {% if (file.error) { %}
            <td></td>
            <td class="name">
              <span>{%= file.name %}</span>
            </td>
            <td class="size">
              <span>{%= o.formatFileSize(file.size) %}</span>
            </td>
        <td class="error" colspan="2">
          <span class="label
                       label-important">{%=locale.fileupload.error%}</span>
          {%= locale.fileupload.errors[file.error] || file.error%}
        </td>
        {% } else { %}
            <td class="preview">{% if (file.thumbnail_url) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
            {% } %}</td>
            <td class="name">
                <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
            </td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td colspan="2"></td>
        {% } %}
        <td class="delete">
            <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
                <i class="icon-trash icon-white"></i>
                <span>{%= locale.fileupload.destroy %}</span>
            </button>
            <input type="checkbox" name="delete" value="1">
        </td>
    </tr>
{% } %}
</script>

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => 'form-horizontal',
      :multipart => true } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :customer_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :customer_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :duration, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :duration, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :tags, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tags, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :status, :class => 'check_box' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:customer_name) %></th>
      <th><%= model_class.human_attribute_name(:duration) %></th>
      <th><%= model_class.human_attribute_name(:tags) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.id, project_path(project) %></td>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.customer_name %></td>
        <td><%= project.duration %></td>
        <td><%= project.tags %></td>
        <td><%= project.status %></td>
        <td><%=l project.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_project_path(project), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      project_path(project),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @project.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @project.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:customer_name) %>:</strong></dt>
  <dd><%= @project.customer_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:duration) %>:</strong></dt>
  <dd><%= @project.duration %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tags) %>:</strong></dt>
  <dd><%= @project.tags %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @project.status %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
      projects_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
      edit_project_path(@project), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
      project_path(@project),
      :method => 'delete',
      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
      :class => 'btn btn-danger' %>
</div>

<%= render 'file_upload' %>